apiVersion: v1
kind: Service
metadata:
  name: <Nama service>
spec:
  type: NodePort
  ports:
  - name: http
    port: <External port yang bissa di akses dari public network>
    targetPort: <Internal port yang akan kita tuju>
  selector:
    name: <Nama service>